### ISSUE TITLE
Logo looks a bit sketchy on high-DPI screens

### ISSUE THREAD

**Issue by DanielOaks** [inspircd/old-website#11]
On high-DPI screens (such as phones and such) the logo on the site looks pretty pixelated. If anyone has a vector of the logo, feel free to throw it over and I can look at this.

**Comment by sadiepowell** [comment]
I can confirm that this is a problem on at least iOS.

All of the images look a bit dodgy on high DPI screens actually.

**Comment by attilamolnar** [comment]
@rolandhegedus can you look at this issue please?

**Comment by rolandhegedus** [comment]
png sprites changed to svg sprites
