### ISSUE TITLE
Request: change layout for the wiki

### ISSUE THREAD

**Issue by DjSlash** [inspircd/old-website#4]
Hey, this is somewhat related to #2 - but this request is taking it a bit further. We should make the wiki a good place to read and currently it's not.
If you take this:
![screenshot - 07202013 - 08 51 23 am](https://f.cloud.github.com/assets/538802/829854/4ac2d638-f109-11e2-8ded-597935d1aa65.png)
Over this:
![screenshot - 07202013 - 08 51 58 am](https://f.cloud.github.com/assets/538802/829855/4aefb716-f109-11e2-94a6-efbf110f2977.png)
I would prefer to have something similar as the former.

Things that should be fixed at least are the identations of the headings, font-size, the syntax portions should have at least newlines when they are in the block.

**Comment by sadiepowell** [comment]
We have migrated back to the old wiki which has better formatting so i'm going to close this.
