### ISSUE TITLE
Modules linked to in FAQ result to 404 error.

### ISSUE THREAD

**Issue by Mikaela** [inspircd/old-website#5]
At http://www.inspircd.org/wiki/FAQ.html links to these modules result GitHub pages 404 error.
- m_chanprotect --> http://www.inspircd.org/wiki/Modules/chanprotect.html
- m_customprefix --> http://www.inspircd.org/wiki/Modules/customprefix.html
- m_override --> http://www.inspircd.org/wiki/Modules/override.html
- m_ident --> http://www.inspircd.org/wiki/Modules/ident.html
- m_cheeseandsandwich --> http://www.inspircd.org/wiki/Modules/cheesesandwich.html

**Comment by sadiepowell** [comment]
We have migrated back to using the old wiki which doesn't have this problem so i'm closing this.
