### ISSUE TITLE
Errorcode 403 Forbidden for wiki.inspircd.org

### ISSUE THREAD

**Issue by shibumi** [inspircd/old-website#6]
Hello,
I can't visit your wiki. I need informations about module m_ssl_gnutls.so I can't find it and install it via modulemanager..

**Comment by sadiepowell** [comment]
It seems to work for me. What URI were you getting that error on?

**Comment by sadiepowell** [comment]
As you haven't responded in over a month i'm going to assume this problem is fixed.
